services:
  sveltekit-app:
    build:
      context: .
      args:
        - FONTAWESOME_TOKEN=${FONTAWESOME_TOKEN}
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_KEY=${SUPABASE_KEY}
        - SEA_TEMP_URL=${SEA_TEMP_URL}
        - TIDE_URL=${TIDE_URL}
    container_name: guernseytides
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SEA_TEMP_URL=${SEA_TEMP_URL}
      - TIDE_URL=${TIDE_URL}
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.routers.guernsey.rule=Host(`seas.gg`)'
      - 'traefik.http.routers.guernsey.entrypoints=websecure'
      - 'traefik.http.routers.guernsey.tls.certresolver=letsencrypt'
      - 'traefik.http.services.guernsey.loadbalancer.server.port=5000'
      - 'traefik.http.middlewares.security-headers.headers.frameDeny=true'
      - 'traefik.http.middlewares.security-headers.headers.sslRedirect=true'
      - 'traefik.http.middlewares.security-headers.headers.browserXssFilter=true'
      - 'traefik.http.routers.guernsey.middlewares=security-headers@docker'
    networks:
      - web
networks:
  web:
    external: true
