services:
  sveltekit-app:
    image: ghcr.io/lukejameson/seas-gg:latest
    build:
      context: .
    container_name: seas-gg
    environment:
      - SEA_TEMP_URL=${SEA_TEMP_URL}
      - TIDE_URL=${TIDE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSL=${POSTGRES_SSL}
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.routers.seas-gg.rule=Host(`seas.gg`)'
      - 'traefik.http.routers.seas-gg.entrypoints=websecure'
      - 'traefik.http.routers.seas-gg.tls.certresolver=letsencrypt'
      - 'traefik.http.services.seas-gg.loadbalancer.server.port=5000'
      - 'traefik.http.middlewares.security-headers.headers.frameDeny=true'
      - 'traefik.http.middlewares.security-headers.headers.sslRedirect=true'
      - 'traefik.http.middlewares.security-headers.headers.browserXssFilter=true'
      - 'traefik.http.routers.seas-gg.middlewares=security-headers@docker'
    networks:
      - web
networks:
  web:
    external: true
