create table
  public.pool_cleaning_dates (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    date date null,
    pools text null,
    constraint pool_cleaning_dates_pkey primary key (id)
  ) tablespace pg_default;