create table
  public.sea_temp (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    date date not null,
    sea_temp_c text null,
    constraint sea_temp_pkey primary key (id),
    constraint sea_temp_date_key unique (date)
  ) tablespace pg_default;