name: Deploy to VPS
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      - name: Install Dependencies
        run: npm ci
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/seas-gg:latest
          build-args: |
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            TIDE_URL=${{ secrets.TIDE_URL }}
            SEA_TEMP_URL=${{secrets.SEA_TEMP_URL}}
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TIDE_URL: ${{ secrets.TIDE_URL }}
          SEA_TEMP_URL: ${{ secrets.SEA_TEMP_URL }}
        with:
          host: ${{ secrets.VPS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          port: ${{secrets.VPS_SSH_PORT}}
          envs: SUPABASE_URL,SUPABASE_KEY,TIDE_URL,SEA_TEMP_URL
          script: |
            cd ~/docker-apps/seas-gg
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/seas-gg:latest
            SUPABASE_URL=$SUPABASE_URL \
            SUPABASE_KEY=$SUPABASE_KEY \
            TIDE_URL=$TIDE_URL \
            SEA_TEMP_URL=$SEA_TEMP_URL \
            docker compose down
            SUPABASE_URL=$SUPABASE_URL \
            SUPABASE_KEY=$SUPABASE_KEY \
            TIDE_URL=$TIDE_URL \
            SEA_TEMP_URL=$SEA_TEMP_URL \
            docker compose up -d
            docker logout ghcr.io